### ISSUE TITLE
Question: how to use PreviewBytes property in VideoAttachment/ImageAttachment?

### ISSUE THREAD

**Issue by Verrok** [JetBrains/space-dotnet-sdk#10]

**Comment by maartenba** [comment]
Hi @Verrok,

Those fields are base64-encoded 32x32 jpg or png, but this may change in the future. Right now it would be advised not do depend on these fields in your code (you can use them but they may be removed/changed)

Hope this helps!

**Comment by Verrok** [comment]
> Hi @Verrok,
> 
> Those fields are base64-encoded 32x32 jpg or png, but this may change in the future. Right now it would be advised not do depend on these fields in your code (you can use them but they may be removed/changed)
> 
> Hope this helps!

thank you!
