### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type ClassNameDtoTypeConverter to type 'System.Text.Json.Serialization.JsonConverter`1[CFValue]'

### ISSUE THREAD

**Issue by Verrok** [JetBrains/space-dotnet-sdk#3]
Trying to get issues with custom field with "Issue List" type
my code: https://pastebin.com/2jHbnPC1
stacktrace: https://hastebin.com/raw/xowezokevu

```
System.InvalidCastException: Unable to cast object of type 'JetBrains.Space.Common.Json.Serialization.Polymorphism.ClassNameDtoTypeConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[JetBrains.Space.Client.CFValue]' while trying to get custom fields
```

**Comment by maartenba** [comment]
Thanks, will investigate!

**Comment by Verrok** [comment]
Forgot to mention that it only occurs on .NET5
With .NETCORE3.1 it works

**Comment by maartenba** [comment]
A new version of the package is now available on NuGet, please give it a try and let us know how it goes?

**Comment by Verrok** [comment]
Working! Thank you for fast fix :)
