### ISSUE TITLE
How to get sub-items

### ISSUE THREAD

**Issue by ArthurVasseur** [JetBrains/space-dotnet-sdk#6]
Hello,

I'm trying to get the sub-items of an isssue, the only thing that is available is `SubItemsCount` and `.WithSubItemsCount()`. Is there missing variable in the issue class and function in `IssuePartialExtensions` ?

**Comment by maartenba** [comment]
Hi @ArthurVasseur! There should also be a `WithSubItemsList()` that you can use on the issue partial. (in the latest release from yesterday), although I'm not 100% sure it is deployed to the service yet. But that will be the extension you are looking for :-)

**Comment by ArthurVasseur** [comment]
The version I have is `1.0.0-beta.v2022.2.0-DEV.107983.9110`, `WithSubItemsList` it's not available in it.
I suppose I have to wait for the new version

**Comment by maartenba** [comment]
It should be there if you add a `using JetBrains.Space.Client.IssuePartialBuilder`, can you try?

**Comment by ArthurVasseur** [comment]
I reinstalled the package it seems to have worked !
Thanks for your help :)

**Comment by ArthurVasseur** [comment]
I have another problem
Here's my code : 
```csharp
await foreach (var issue in project.Planning.Issues.GetAllIssuesAsyncEnumerable(
                   ProjectIdentifier.Key(_projectName), IssuesSorting.UPDATED, true,
                   tags: _tags,
                   partial: _ => _
                       .WithAllFieldsWildcard()
                       .WithCreationTime()
                       .WithDescription()
                       .WithStatus()
                       .WithSprints()
                       .WithCustomFields()
                       .WithChannel()
                       .WithSubItemsCount()
                       .WithSubItemsList(subItem => subItem.WithName().WithDescription().WithRoot())
                       .WithTags(tag => tag.WithName().WithId())
                       .WithAssignee(assignee => assignee.WithName())
               ))
{
    _issues.Add(issue);
}
 ```
 
 If I want to access to the member `SubItemsList` I've got an exception : `JetBrains.Space.Common.PropertyNotRequestedException: The property SubItemsList was not requested in the partial builder for Issue. Use .WithSubItemsList() to include it. Expected full path: Batch1->WithData().WithSubItemsList() at JetBrains.Space.Co…`
   
But I have already call `WithSubItemList(...)`

**Comment by maartenba** [comment]
This may be caused by the `subitemslist` field not yet being exposed by the API. Just checked on my own organization, and it's not yet deployed to Space. Can you check if this is also the case on your organization?

`https://<org>.jetbrains.space/extensions/httpApiPlayground?resource=projects_xxx_planning_issues&endpoint=rest_query`

**Comment by ArthurVasseur** [comment]
Same for me

**Comment by maartenba** [comment]
I'll keep an eye on it and let you now when it goes live 👍

**Comment by ArthurVasseur** [comment]
Okey thanks !

**Comment by maartenba** [comment]
It just appeared on my organization 👍

**Comment by ArthurVasseur** [comment]
Yup, I have it too ! Thanks
